### ISSUE TITLE
Mention registration in Supporting the SCORM Temporal Model

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-SCORM-Profile#16]
I'd like to see context.registration mentioned in section 5.0 SCORM Temporal Model. Registration should be used to link statements relating to a single attempt.

**Comment by creighton** [comment]
see https://github.com/creighton/xAPI-SCORM-Profile/commit/b15f4ab44684336c4fef7576ca1f9c088af44df4

As for using registration for attempt, session, and anything else, we continue to make the distinction with contextActivities, mainly because we can query and filter based on those IRIs (much like registration), due to the case illustrated in the xapi group post: https://groups.google.com/a/adlnet.gov/forum/#!topic/xapi-spec/Pkh0todNUX4
