### ISSUE TITLE
attemptId section in appendix should be replaced by registration section

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-SCORM-Profile#22]
https://github.com/adlnet/xAPI-SCORM-Profile/blob/master/xapi-scorm-profile.md#group-statements-by-attempt-id

context.registration is the standard way of tracking attempts. This can be used as a filter in GET Statements.

**Comment by creighton** [comment]
related to #8 and #16. Basically due to needing to differentiate both attempts and sessions, we need more than the one property context.registration gives us. We don't restrict developers from using context.registration. We just use contextActivities as locations to store attempt and session/SCO IRIs.
